spring:
  mail:
    host: imap.gmail.com
    port: 993
    username: ${RECEIVER_EMAIL_ADDRESS}
    password: ${RECEIVER_EMAIL_PASSWORD}
    properties:
      mail:
        imap:
          ssl:
            enable: true