spring:
  datasource:
    url: jdbc:mysql://localhost:3306/greenwinit_local?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: com.example.green.infra.database.strategy.UpperSnakeNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 35MB

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  storage:
    bucket: local-test-bucket
    base-url: http://localhost:8080/static 