
-- 최신 잔고
-- ========================================
EXPLAIN ANALYZE
SELECT BALANCE_AFTER
FROM POINT_TRANSACTIONS
WHERE MEMBER_ID = 5000
ORDER BY POINT_TRANSACTION_ID DESC
    LIMIT 1;

-- 포인트 내역 요약 (서브쿼리 + 집계)
-- ========================================
EXPLAIN ANALYZE
SELECT
    COALESCE(
            (SELECT pt2.BALANCE_AFTER
             FROM POINT_TRANSACTIONS pt2
             WHERE pt2.MEMBER_ID = 5000
             ORDER BY pt2.POINT_TRANSACTION_ID DESC
            LIMIT 1), 0
    ) as current_balance,
    COALESCE(SUM(CASE WHEN pt.TYPE = 'EARN' THEN pt.POINT_AMOUNT ELSE 0 END), 0) as total_earned,
    COALESCE(SUM(CASE WHEN pt.TYPE = 'SPEND' THEN pt.POINT_AMOUNT ELSE 0 END), 0) as total_spent
FROM POINT_TRANSACTIONS pt
WHERE pt.MEMBER_ID = 5000;

-- 포인트 내역 조회 (커서 페이징)
-- ========================================
EXPLAIN ANALYZE
SELECT
    POINT_TRANSACTION_ID,
    TARGET_TYPE,
    DESCRIPTION,
    CASE WHEN TYPE='EARN' THEN POINT_AMOUNT ELSE 0 END as earn_amount,
    CASE WHEN TYPE='SPEND' THEN POINT_AMOUNT ELSE 0 END as spend_amount,
    BALANCE_AFTER,
    CREATED_DATE
FROM POINT_TRANSACTIONS
WHERE MEMBER_ID = 5000
  AND POINT_TRANSACTION_ID < 400000
ORDER BY POINT_TRANSACTION_ID DESC
    LIMIT 10;

-- 포인트 내역 조회 (커서 페이징) TYPE filter
-- ========================================
EXPLAIN ANALYZE
SELECT
    POINT_TRANSACTION_ID,
    TARGET_TYPE,
    DESCRIPTION,
    POINT_AMOUNT,
    BALANCE_AFTER,
    CREATED_DATE
FROM POINT_TRANSACTIONS
WHERE MEMBER_ID = 5000
  AND TYPE = 'EARN'
  AND POINT_TRANSACTION_ID < 400000
ORDER BY POINT_TRANSACTION_ID DESC
    LIMIT 10;

-- 여러 사용자 별 포인트 지급내역
-- ========================================
EXPLAIN ANALYZE
SELECT MEMBER_ID, SUM(POINT_AMOUNT) as total_earned
FROM POINT_TRANSACTIONS
WHERE TYPE = 'EARN'
  AND MEMBER_ID IN (1000, 2000, 3000, 4000, 5000)
GROUP BY MEMBER_ID;

-- 사용자 포인트 내역 조회 (관리자 페이징)
-- ========================================
EXPLAIN ANALYZE
SELECT
    POINT_TRANSACTION_ID,
    MEMBER_ID,
    TARGET_TYPE,
    DESCRIPTION,
    POINT_AMOUNT,
    BALANCE_AFTER,
    TYPE,
    CREATED_DATE
FROM POINT_TRANSACTIONS
WHERE MEMBER_ID = 5000
ORDER BY POINT_TRANSACTION_ID DESC
    LIMIT 20 OFFSET 0;

-- 엑셀 다운로드용 전체 조회
-- ========================================
EXPLAIN ANALYZE
SELECT
    POINT_TRANSACTION_ID,
    TARGET_TYPE,
    DESCRIPTION,
    POINT_AMOUNT,
    BALANCE_AFTER,
    TYPE,
    CREATED_DATE
FROM POINT_TRANSACTIONS
WHERE MEMBER_ID = 5000
ORDER BY POINT_TRANSACTION_ID DESC;