
ALTER TABLE FILES ADD COLUMN IS_SYSTEM_FILE BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE FILES 
SET IS_SYSTEM_FILE = TRUE,
    FILE_STATUS = 'PERMANENT',
    DELETED = FALSE
WHERE FILE_KEY = 'https://static.greenwinit.store/images/profile/2b/20250820/5aa9293e_1755672635950.png';

CREATE INDEX idx_system_files ON FILES(IS_SYSTEM_FILE) WHERE IS_SYSTEM_FILE = TRUE;