name: CD Deploy

# 워크플로우 실행 조건
# PR이 main 브랜치로 merge될 때만 실행
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:
  deploy:
    # PR이 merge된 경우에만 실행
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 전체 테스트 실행 (단위 테스트 + 통합 테스트)
      - name: Run All Tests
        run: ./gradlew test

      # 테스트 커버리지 리포트 생성
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport -x jacocoTestCoverageVerification

      # 코드 스타일 검사
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      # 프로젝트 빌드
      - name: Build Project
        run: ./gradlew clean build -x test

      # 환경 변수 설정
      - name: GitHub Secrets To .env
        run: |
          echo "DB_TYPE=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> .env
          echo "STORAGE_BASE_URL=${{ secrets.STORAGE_BASE_URL }}" >> .env

      - name: Copy artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            build/libs/green*.jar
            .env
          target: "~/backend"

      - name: Run reload.sh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            chmod +x ~/reload.sh
            ~/reload.sh
