name: CD Deploy

# 워크플로우 실행 조건
# PR이 main 브랜치로 merge될 때만 실행
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # 환경변수 한 파일로 관리
      - name: Create .env file from GitHub Secret
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV_FILE }}
          EOF

      # 프로젝트 빌드
      - name: Build Project
        run: ./gradlew clean build -x test

      # JAR 파일 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build/libs/green-0.0.1-SNAPSHOT.jar"
          target: "~/"
          strip_components: 2

      # .env 파일 복사
      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".env"
          target: "~/"

      # EC2에서 애플리케이션 재시작
      - name: Run reload.sh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo chmod +x ~/reload.sh
            ~/reload.sh
