name: Integration Test

on:
  pull_request:
    types: [labeled, synchronize]
    branches: [ "main" ]

jobs:
  integration-test:
    # 1. 라벨을 붙였을 때 (labeled 이벤트)
    # 2. 라벨이 있는 상태에서 새로운 커밋이 푸시되었을 때 (synchronize 이벤트)
    if: |
      github.event_name == 'pull_request' && 
      contains(github.event.pull_request.labels.*.name, 'run-integration-test') &&
      (github.event.action == 'labeled' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run All Tests
        run: ./gradlew test

      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport -x jacocoTestCoverageVerification

      - name: Add Integration Test Coverage Comment
        uses: madrapps/jacoco-report@v1.5
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          title: "Integration Test Coverage Report"
          update-comment: true

      - name: Build Project
        run: ./gradlew clean build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar 